name: Build with MPLAB X and XC8
description: This action builds a MPLAB X / XC8 project in a Linux container.
branding:
  icon: package
  color: gray-dark
inputs:
  project:
    description: Project folder location
    required: true
  configurations:
    description: Space separated list of configurations to build
    required: true
    default: default
  mplabx_version:
    description: Version of MPLAB X to use
    required: true
    default: "6.05"
  xc8_version:
    description: Version of the XC8 compiler to use
    required: true
    default: "2.40"
  mplab_download_url:
    description: Complete download URL for MPLAB X
    required: true
  device_pack:
    description: "Device pack to install"
  device_pack_version:
    description: "Version of device pack to install"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.mplabx_version }}
    - ${{ inputs.xc8_version }}
    - ${{ inputs.project }}
    - ${{ inputs.configurations }}
    - ${{ inputs.mplab_download_url }}
    - ${{ inputs.device_pack }}
    - ${{ inputs.device_pack_version }}
